---
- name: Eliminar grupo de recursos
  hosts: localhost
  tasks:
    - name: Eliminando el grupo de recursos...
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent
        force_delete_nonempty: yes
...
